server.port=8086
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.mvc.throw-exception-if-no-handler-found=true

spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.web=DEBUG

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.security.user.name=sonam
spring.security.user.password=Sonam@1234

jwt.secret=SonamSuperSecureJWTSecretKey@2026#VeryLongKey12345
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8086/login/oauth2/code/google