package com.example.QuantityMeasurementApp.repository;

import com.example.QuantityMeasurementApp.entity.QuantityMeasurementEntity;
import com.example.QuantityMeasurementApp.exception.DatabaseException;
import com.example.QuantityMeasurementApp.utils.ConnectionPool;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class QuantityMeasurementDatabaseRepository implements IQuantityMeasurementRepository {

	public QuantityMeasurementDatabaseRepository() {
		initDB();
	}

	private void initDB() {
		try (Connection con = ConnectionPool.getConnection(); Statement stmt = con.createStatement()) {

			stmt.execute("DROP TABLE IF EXISTS quantity_measurement");

			stmt.execute("CREATE TABLE quantity_measurement (" + "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
					+ "measurement_type VARCHAR(50)," + "operation_type VARCHAR(50)," + "value1 DOUBLE,"
					+ "value2 DOUBLE," + "result BOOLEAN)");

		} catch (Exception e) {
			throw new DatabaseException("DB Init Failed", e);
		}
	}

	@Override
	public void save(QuantityMeasurementEntity entity) {
		String sql = "INSERT INTO quantity_measurement " + "(measurement_type, operation_type, value1, value2, result) "
				+ "VALUES (?, ?, ?, ?, ?)";

		try (Connection con = ConnectionPool.getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {

			ps.setString(1, entity.getMeasurementType());
			ps.setString(2, entity.getOperationType());
			ps.setDouble(3, entity.getValue1());
			ps.setDouble(4, entity.getValue2());
			ps.setBoolean(5, entity.isResult());

			ps.executeUpdate();

		} catch (Exception e) {
			throw new DatabaseException("Save failed", e);
		}
	}

	@Override
	public List<QuantityMeasurementEntity> getAll() {
		List<QuantityMeasurementEntity> list = new ArrayList<>();
		String sql = "SELECT * FROM quantity_measurement";

		try (Connection con = ConnectionPool.getConnection();
				PreparedStatement ps = con.prepareStatement(sql);
				ResultSet rs = ps.executeQuery()) {

			while (rs.next()) {
				list.add(new QuantityMeasurementEntity(rs.getString("measurement_type"), rs.getString("operation_type"),
						rs.getDouble("value1"), rs.getDouble("value2"), rs.getBoolean("result")));
			}

		} catch (Exception e) {
			throw new DatabaseException("Fetch failed", e);
		}

		return list;
	}

	@Override
	public int count() {
		String sql = "SELECT COUNT(*) FROM quantity_measurement";

		try (Connection con = ConnectionPool.getConnection();
				PreparedStatement ps = con.prepareStatement(sql);
				ResultSet rs = ps.executeQuery()) {

			if (rs.next())
				return rs.getInt(1);

		} catch (Exception e) {
			throw new DatabaseException("Count failed", e);
		}

		return 0;
	}

	@Override
	public void deleteAll() {
		String sql = "DELETE FROM quantity_measurement";

		try (Connection con = ConnectionPool.getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {

			ps.executeUpdate();

		} catch (Exception e) {
			throw new DatabaseException("Delete failed", e);
		}
	}
}